name: scholarsync
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  calendar_view: ^1.0.3
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  expandable_text: ^2.3.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  fpdart: ^0.6.0
  image_picker: ^1.0.1
  intl: ^0.18.0
  permission_handler: ^10.2.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.2
  phosphor_flutter: ^2.0.0
  riverpod: ^2.4.0
  provider: ^6.0.5
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  url_launcher: ^6.1.14
  firebase_messaging: ^14.6.8
  cached_network_image: ^3.2.3
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/
